"""Mining-domain models, deterministic primitives, and mining orchestration."""

from hashphere.mining.chunks import (
    ChunkedMiningError,
    ChunkedMiningObserver,
    ChunkedMiningPlan,
    ChunkedMiningResult,
    ChunkedMiningValidationError,
    NullChunkedMiningObserver,
    run_chunked_mining,
)
from hashphere.mining.coinbase import (
    CoinbaseError,
    CoinbaseValidationError,
    build_coinbase_transaction,
    hash_coinbase_transaction,
)
from hashphere.mining.continuous import (
    ContinuousMiningError,
    ContinuousMiningObserver,
    ContinuousMiningOutcome,
    ContinuousMiningPlan,
    ContinuousMiningResult,
    ContinuousMiningValidationError,
    NullContinuousMiningObserver,
    StopController,
    StopToken,
    run_continuous_mining,
)
from hashphere.mining.header import (
    BlockHeaderError,
    BlockHeaderValidationError,
    hash_block_header,
    serialize_block_header,
)
from hashphere.mining.job import (
    MiningJob,
    MiningJobAssembler,
    MiningJobError,
    MiningJobStateError,
    MiningJobValidationError,
)
from hashphere.mining.merkle import (
    MerkleError,
    MerkleValidationError,
    calculate_merkle_root,
)
from hashphere.mining.search import (
    NonceSearchError,
    NonceSearchMatch,
    NonceSearchResult,
    NonceSearchValidationError,
    PreparedMiningWork,
    prepare_mining_work,
    search_nonce_range,
)
from hashphere.mining.target import (
    TargetError,
    TargetValidationError,
    block_hash_to_int,
    decode_compact_target,
    difficulty_to_share_target,
    hash_meets_target,
)

__all__ = [
    "BlockHeaderError",
    "BlockHeaderValidationError",
    "CoinbaseError",
    "CoinbaseValidationError",
    "ChunkedMiningError",
    "ChunkedMiningObserver",
    "ChunkedMiningPlan",
    "ChunkedMiningResult",
    "ChunkedMiningValidationError",
    "ContinuousMiningError",
    "ContinuousMiningObserver",
    "ContinuousMiningOutcome",
    "ContinuousMiningPlan",
    "ContinuousMiningResult",
    "ContinuousMiningValidationError",
    "MiningJob",
    "MiningJobAssembler",
    "MiningJobError",
    "MiningJobStateError",
    "MiningJobValidationError",
    "MerkleError",
    "MerkleValidationError",
    "NonceSearchError",
    "NonceSearchMatch",
    "NonceSearchResult",
    "NonceSearchValidationError",
    "NullChunkedMiningObserver",
    "NullContinuousMiningObserver",
    "PreparedMiningWork",
    "StopController",
    "StopToken",
    "TargetError",
    "TargetValidationError",
    "block_hash_to_int",
    "build_coinbase_transaction",
    "calculate_merkle_root",
    "decode_compact_target",
    "difficulty_to_share_target",
    "hash_block_header",
    "hash_coinbase_transaction",
    "hash_meets_target",
    "prepare_mining_work",
    "run_chunked_mining",
    "run_continuous_mining",
    "search_nonce_range",
    "serialize_block_header",
]
