"""Hashphere configuration."""

from hashphere.config.bitcoin_rpc import (
    DEFAULT_BITCOIN_RPC_HOST,
    DEFAULT_BITCOIN_RPC_PORT,
    DEFAULT_BITCOIN_RPC_TIMEOUT_SECONDS,
    BitcoinRpcSettings,
)
from hashphere.config.profile import (
    CUDA_THREADS_PER_BLOCK_CHOICES,
    DEFAULT_CUDA_THREADS_PER_BLOCK,
    MAX_INTER_RANGE_DELAY_SECONDS,
    PROFILE_NAMES,
    ComputeProfileCapabilityProvider,
    ComputeProfileError,
    ComputeProfileOverrides,
    ComputeProfileResolutionError,
    ComputeProfileValidationError,
    ResolvedComputeProfile,
    parse_compute_profile,
    resolve_compute_profile,
)
from hashphere.config.settings import (
    DEFAULT_COMPUTE_WORKERS,
    DEFAULT_CUDA_DEVICE,
    DEFAULT_CUDA_DEVICES,
    DEFAULT_SEARCH_STRATEGY,
    MAX_COMPUTE_WORKERS,
    MAX_CUDA_DEVICE,
    MAX_CUDA_DEVICES,
    Settings,
    parse_compute_profile_overrides_from_env,
    parse_cuda_devices,
)
from hashphere.config.solo import (
    BITCOIN_RPC_CHECK_FLAG,
    BLOCK_SUBMISSION_FLAG,
    SOLO_PAYOUT_ADDRESS,
    TRUE_SOLO_FLAG,
    TRUE_SOLO_HASHING_FLAG,
    SoloCommandSettings,
    require_exact_opt_in,
)

__all__ = [
    "CUDA_THREADS_PER_BLOCK_CHOICES",
    "BitcoinRpcSettings",
    "BITCOIN_RPC_CHECK_FLAG",
    "BLOCK_SUBMISSION_FLAG",
    "ComputeProfileCapabilityProvider",
    "ComputeProfileError",
    "ComputeProfileOverrides",
    "ComputeProfileResolutionError",
    "ComputeProfileValidationError",
    "DEFAULT_COMPUTE_WORKERS",
    "DEFAULT_BITCOIN_RPC_HOST",
    "DEFAULT_BITCOIN_RPC_PORT",
    "DEFAULT_BITCOIN_RPC_TIMEOUT_SECONDS",
    "DEFAULT_CUDA_DEVICE",
    "DEFAULT_CUDA_DEVICES",
    "DEFAULT_CUDA_THREADS_PER_BLOCK",
    "DEFAULT_SEARCH_STRATEGY",
    "MAX_COMPUTE_WORKERS",
    "MAX_CUDA_DEVICE",
    "MAX_CUDA_DEVICES",
    "MAX_INTER_RANGE_DELAY_SECONDS",
    "PROFILE_NAMES",
    "ResolvedComputeProfile",
    "SOLO_PAYOUT_ADDRESS",
    "Settings",
    "SoloCommandSettings",
    "TRUE_SOLO_FLAG",
    "TRUE_SOLO_HASHING_FLAG",
    "parse_cuda_devices",
    "parse_compute_profile",
    "parse_compute_profile_overrides_from_env",
    "resolve_compute_profile",
    "require_exact_opt_in",
]
