"""Bitcoin Core true-solo primitives, isolated from Stratum."""

from hashorb.bitcoin.block import (
    SoloBlockCandidate,
    SoloBlockError,
    SoloWorkVariant,
    assemble_solo_block,
    prepare_solo_work,
    serialize_solo_header,
)
from hashorb.bitcoin.coinbase import (
    CoinbaseConstructionError,
    SoloCoinbase,
    build_solo_coinbase,
    encode_push_data,
    encode_script_number,
    next_coinbase_extra_nonce,
)
from hashorb.bitcoin.rpc import (
    BitcoinCoreRpcClient,
    BitcoinCoreTemplateClient,
    BitcoinRpcAuthenticationError,
    BitcoinRpcError,
    BitcoinRpcProtocolError,
    BitcoinRpcRemoteError,
    BitcoinRpcTransportError,
    BlockchainInfo,
    HttpResponse,
    PayoutDestination,
    ProposalOutcome,
    SubmissionOutcome,
    UrllibBitcoinRpcTransport,
)
from hashorb.bitcoin.serialization import (
    BitcoinSerializationError,
    ByteReader,
    encode_compact_size,
)
from hashorb.bitcoin.solo import (
    NullSoloMiningObserver,
    SoloMiningError,
    SoloMiningObserver,
    SoloMiningOutcome,
    SoloMiningPlan,
    SoloMiningResult,
    SoloMiningValidationError,
    run_solo_mining,
)
from hashorb.bitcoin.template import (
    BlockTemplate,
    BlockTemplateError,
    TemplateTransaction,
    calculate_hash_merkle_root,
    parse_block_template,
)
from hashorb.bitcoin.transaction import (
    BitcoinTransactionError,
    ParsedTransaction,
    parse_transaction,
)

__all__ = [
    "BitcoinCoreRpcClient",
    "BitcoinCoreTemplateClient",
    "BitcoinSerializationError",
    "BitcoinTransactionError",
    "BitcoinRpcAuthenticationError",
    "BitcoinRpcError",
    "BitcoinRpcProtocolError",
    "BitcoinRpcRemoteError",
    "BitcoinRpcTransportError",
    "BlockchainInfo",
    "BlockTemplate",
    "BlockTemplateError",
    "ByteReader",
    "CoinbaseConstructionError",
    "HttpResponse",
    "NullSoloMiningObserver",
    "PayoutDestination",
    "ParsedTransaction",
    "ProposalOutcome",
    "SoloBlockCandidate",
    "SoloBlockError",
    "SoloCoinbase",
    "SoloMiningError",
    "SoloMiningObserver",
    "SoloMiningOutcome",
    "SoloMiningPlan",
    "SoloMiningResult",
    "SoloMiningValidationError",
    "SoloWorkVariant",
    "SubmissionOutcome",
    "TemplateTransaction",
    "UrllibBitcoinRpcTransport",
    "assemble_solo_block",
    "build_solo_coinbase",
    "calculate_hash_merkle_root",
    "encode_compact_size",
    "encode_push_data",
    "encode_script_number",
    "next_coinbase_extra_nonce",
    "parse_block_template",
    "parse_transaction",
    "prepare_solo_work",
    "run_solo_mining",
    "serialize_solo_header",
]
